# https://fabricmc.net/develop/

[versions]

# Minecraft / Loaders
minecraft = "1.20.1"
fabric-loader = "0.14.22"
fabric-api = "0.88.1+1.20.1"
fabric-loom = "1.0-SNAPSHOT"

# Dependencies
jsr305 = "3.0.2"

# Mod dependencies
modmenu = "5.0.1"
cloth-config = "9.0.94"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
loom = { id = "fabric-loom", version.ref = "fabric-loom" }
