# https://fabricmc.net/develop/

[versions]

# Minecraft / Loaders
minecraft = "1.19.2"
fabric-loader = "0.14.9"
fabric-api = "0.61.0+1.19.2"
fabric-kotlin = "1.8.0+kotlin.1.7.0"
fabric-loom = "1.0-SNAPSHOT"

# Dependencies
log4j2 = "2.18.0"
jsr305 = "3.0.2"

# Mod dependencies
modmenu = "4.0.6"
cloth-config = "8.2.88"

# Publish
curseforge-publish = "0.1.0"


[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc.fabric-language-kotlin", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }

log4j2 = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j2" }
findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
loom = { id = "fabric-loom", version.ref = "fabric-loom" }
curseforge = { id = "io.github.themrmilchmann.curseforge-publish", version.ref = "curseforge-publish" }
